// <auto-generated />
using System;
using CapitalEuropeiaGuarda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CapitalEuropeiaGuarda.Migrations
{
    [DbContext(typeof(CapitalEuropeiaGuardaContext))]
    [Migration("20210109234810_Mig2")]
    partial class Mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CapitalEuropeiaGuarda.Models.Hoteis", b =>
                {
                    b.Property<int>("HoteisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoCurta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoteisId");

                    b.ToTable("Hoteis");
                });

            modelBuilder.Entity("CapitalEuropeiaGuarda.Models.PontoInteresse", b =>
                {
                    b.Property<int>("PontoInteresseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoCurta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PontoInteresseId");

                    b.ToTable("PontoInteresse");
                });

            modelBuilder.Entity("CapitalEuropeiaGuarda.Models.PontoInteressePorHotel", b =>
                {
                    b.Property<int>("PontoInteressePorHotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HoteisId")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("PontoInteresseId")
                        .HasColumnType("int");

                    b.HasKey("PontoInteressePorHotelId");

                    b.HasIndex("HoteisId");

                    b.HasIndex("PontoInteresseId");

                    b.ToTable("PontoInteressePorHotel");
                });

            modelBuilder.Entity("CapitalEuropeiaGuarda.Models.ReservaExcursao", b =>
                {
                    b.Property<int>("ReservaExcursaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("DataCancelar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataReserva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumPessoas")
                        .HasColumnType("int");

                    b.HasKey("ReservaExcursaoId");

                    b.ToTable("ReservaExcursao");
                });

            modelBuilder.Entity("CapitalEuropeiaGuarda.Models.Turista", b =>
                {
                    b.Property<int>("TuristaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nif")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telemovel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TuristaId");

                    b.ToTable("Turista");
                });

            modelBuilder.Entity("CapitalEuropeiaGuarda.Models.aluguercarros", b =>
                {
                    b.Property<int>("aluguercarrosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LinkReserva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lugares")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("aluguercarrosId");

                    b.ToTable("aluguercarros");
                });

            modelBuilder.Entity("CapitalEuropeiaGuarda.Models.PontoInteressePorHotel", b =>
                {
                    b.HasOne("CapitalEuropeiaGuarda.Models.Hoteis", "Hoteis")
                        .WithMany("PontoInteressePorHoteis")
                        .HasForeignKey("HoteisId");

                    b.HasOne("CapitalEuropeiaGuarda.Models.PontoInteresse", "PontoInteresse")
                        .WithMany("HoteisPorPontoInteresse")
                        .HasForeignKey("PontoInteresseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
